version: '2.4'

services:
  app:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy

    shm_size: '30gb'
    volumes:
      - .:/srv
      - ./store:/kaggle
    runtime: nvidia
    environment:
      - KAGGLE_USERNAME
      - KAGGLE_KEY
      - KAGGLE_PROXY
      - http_proxy
      - https_proxy
